server:
  port: 8080

spring:
  application:
    name: ai
  ai:
    openai:
      api-key: 
      # Cover Design 전용 설정
      cover:
        model: dall-e-3
        quality: standard
        size: 1024x1024
        style: vivid
      # AI Summary 전용 설정  
      summary:
        model: gpt-4
        temperature: 0.7
        max-tokens: 1000
      # Genre Classification 전용 설정
      genre:
        model: gpt-4
        temperature: 0.3
        max-tokens: 50
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: ai
#<<< EDA / Topic Name
          destination: thminiprojthebook
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: thminiprojthebook
#>>> EDA / Topic Name
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
    port: 8084
---

spring:
  profiles: docker
  ai:
    openai:
      api-key: 
      # Cover Design 전용 설정
      cover:
        model: dall-e-3
        quality: standard
        size: 1024x1024
        style: vivid
      # AI Summary 전용 설정  
      summary:
        model: gpt-4
        temperature: 0.7
        max-tokens: 1000
      # Genre Classification 전용 설정
      genre:
        model: gpt-4
        temperature: 0.3
        max-tokens: 50
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: ai
          destination: thminiprojthebook
          contentType: application/json
        event-out:
          destination: thminiprojthebook
          contentType: application/json


